sudo: require
services:
  - docker

before_install:
  - docker build -t nageshvashist/docker-repo -f Dockerfile.dev .
script:
  - docker run nageshvashist/docker-repo npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app:  docker-react 
  env: DockerReact-env
  bucket_name: elasticbeanstalk-ap-south-1-842693259954
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
